[supervisord]
nodaemon=true
user=steam
logfile=/tmp/supervisord.log
logfile_maxbytes=0

[program:manager_api]
command=python3 -u /app/manager_api.py
directory=/app
autostart=true
autorestart=true
user=steam
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:manager_tasks]
command=python3 -u /app/manager_tasks.py
directory=/app
autostart=true
autorestart=true
user=steam
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:manager_game]
command=python3 -u /app/manager_game.py
directory=/app
autostart=true
autorestart=true
user=steam
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
