[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:flask_app]
command=/usr/bin/python3 /app/app.py
directory=/app
autostart=true
autorestart=true
user=steam
stdout_logfile=/var/log/supervisor/flask_app.log
stderr_logfile=/var/log/supervisor/flask_app_error.log
environment=PYTHONUNBUFFERED="1"

[program:server_monitor]
command=/usr/bin/python3 /app/server_monitor.py
directory=/app
autostart=true
autorestart=true
user=steam
stdout_logfile=/var/log/supervisor/server_monitor.log
stderr_logfile=/var/log/supervisor/server_monitor_error.log
environment=PYTHONUNBUFFERED="1"
