#!/usr/bin/env python3
# Game Server Configuration
import os

# Database Configuration
DATABASE_URL = os.getenv('DATABASE_URL', 'mysql+pymysql://safezone:safezone@db/safezone')
DATABASE_POOL_SIZE = int(os.getenv('DATABASE_POOL_SIZE', '64'))

# Cache Configuration
CACHE_URL = os.getenv('CACHE_URL', 'redis://cache:6379/0')
CACHE_MAX_CONNECTIONS = int(os.getenv('CACHE_MAX_CONNECTIONS', '64'))
CACHE_HEALTH_CHECK_INTERVAL = int(os.getenv('CACHE_HEALTH_CHECK_INTERVAL', '30'))

# Manager for API Configuration
MANAGER_API_PORT = int(os.getenv('MANAGER_API_PORT', '5000'))
MANAGER_API_HOST = os.getenv('MANAGER_API_HOST', '0.0.0.0')
MANAGER_API_TOKEN = os.getenv('MANAGER_API_TOKEN', '')
MANAGER_API_TOKEN = MANAGER_API_TOKEN if MANAGER_API_TOKEN else None

# Steam Configuration
STEAM_APP_ID = int(os.getenv('STEAM_APP_ID', '380870')) # 380870 is Project Zomboid
STEAM_APP_BETA = os.getenv('STEAM_APP_BETA', '') # 42.13.1
STEAM_APP_BETA = STEAM_APP_BETA if STEAM_APP_BETA else None
STEAM_INSTALL_DIR = os.getenv('STEAM_INSTALL_DIR', '/opt/steam-apps')

# Where Project Zomboid keeps its data. Saves are expected at
# $ZOMBOID_DATA_DIR/Saves/Multiplayer/<server name> - the one path here most
# likely to differ between installs.
ZOMBOID_DATA_DIR = os.getenv('ZOMBOID_DATA_DIR', '/home/steam/Zomboid')
# The game server runs beside this manager in the same container, so RCON is a
# loopback connection.
RCON_HOST = os.getenv('RCON_HOST', '127.0.0.1')
# The launch script. SteamCMD installs with `+force_install_dir STEAM_INSTALL_DIR`,
# so the script lands at the install root - but a library-style install puts it
# under `steamapps/common/Project Zomboid Dedicated Server/` instead. This was
# carrying a "points to the wrong server" TODO; making it configurable means a
# wrong guess is one environment variable, not a code change.
SERVER_SCRIPT = os.getenv(
    'SERVER_SCRIPT', os.path.join(STEAM_INSTALL_DIR, 'start-server.sh')
)
# The JVM heap ceiling for the game server, e.g. '4g'. Project Zomboid ships
# `-Xmx8g`, and a host that cannot back 8GB does not get an error: the kernel's
# OOM killer takes the JVM mid-boot, the shell reports "Killed", and the log
# just stops. Blank leaves the installed value alone.
GAME_SERVER_MAX_HEAP = os.getenv('GAME_SERVER_MAX_HEAP', '')
# Garbage collector: Z, G1, Parallel or Serial. The game ships ZGC, which wants
# a large heap and cores to spare for its concurrent work - on a small or older
# machine G1 costs less to run and reserves less memory. Blank keeps the
# installed collector.
GAME_SERVER_GC = os.getenv('GAME_SERVER_GC', '')
# Where those launch parameters live - pzexe reads its `vmArgs` from this file,
# which is how `-Xmx` is set for a dedicated server.
LAUNCH_PARAMS_FILE = os.getenv(
    'LAUNCH_PARAMS_FILE', os.path.join(STEAM_INSTALL_DIR, 'ProjectZomboid64.json')
)
# World archives. Should be its own volume: a backup sharing a volume with the
# thing it protects is not a backup.
BACKUP_DIR = os.getenv('BACKUP_DIR', '/backups')
# How many archives to keep per server after a new one is taken.
BACKUP_KEEP = int(os.getenv('BACKUP_KEEP', '10'))
# Seconds to let a running server flush to disk after `save` before archiving.
BACKUP_QUIESCE_SECONDS = int(os.getenv('BACKUP_QUIESCE_SECONDS', '10'))

# In-game item catalog, behind the item picker in Admin > Rewards and
# Admin > Give. Fetched from PZwiki's autogenerated item list - one request for
# the whole set, and it carries the game version it was generated from. Lives
# here rather than on the backend because the backend has no egress at all.
# Base-game items only; modded ids are still typed by hand.
ITEM_CATALOG_URL = os.getenv(
    'ITEM_CATALOG_URL',
    'https://pzwiki.net/w/index.php?title=PZwiki:Item_list&action=raw'
)
# Icons are referenced by file name; `Special:FilePath` redirects to the real
# image without needing MediaWiki's hashed directory layout.
ITEM_CATALOG_ICON_BASE = os.getenv(
    'ITEM_CATALOG_ICON_BASE',
    'https://pzwiki.net/w/index.php?title=Special:FilePath/'
)
# A week. Item ids change only when the game does.
ITEM_CATALOG_TTL = int(os.getenv('ITEM_CATALOG_TTL', '604800'))
ITEM_CATALOG_TIMEOUT = float(os.getenv('ITEM_CATALOG_TIMEOUT', '30'))

# Community loot-box configs, behind "Import from community" in Admin > Loot
# Boxes. A curated set of box configurations (rewards + drop weights) published
# as JSON on GitHub, so an operator can seed a season without hand-building a
# pool. Fetched here, not on the backend, for the same reason as the item
# catalog: the backend has no egress. Base URL is a directory; the code appends
# `list.json` (the index) and `<id>.json` (one config).
REWARD_BOXES_BASE_URL = os.getenv(
    'REWARD_BOXES_BASE_URL',
    'https://raw.githubusercontent.com/gramthanos/Project-Safezone/main/community/reward-boxes/'
)
# An hour. Curated, but new boxes should show up the same day they are added.
REWARD_BOXES_TTL = int(os.getenv('REWARD_BOXES_TTL', '3600'))
REWARD_BOXES_TIMEOUT = float(os.getenv('REWARD_BOXES_TIMEOUT', '15'))

# Community server-config templates, behind "Templates" in Admin > Servers >
# config. A curated set of INI presets (gameplay tuning, mod lists) published as
# JSON on GitHub, so an operator can adopt a known-good ruleset without editing
# dozens of keys by hand. Fetched here, not on the backend, for the same reason
# as the reward boxes: the backend has no egress. Base URL is a directory; the
# code appends `list.json` (the index) and `<id>.json` (one template).
SERVER_TEMPLATES_BASE_URL = os.getenv(
    'SERVER_TEMPLATES_BASE_URL',
    'https://raw.githubusercontent.com/gramthanos/Project-Safezone/main/community/server-templates/'
)
SERVER_TEMPLATES_TTL = int(os.getenv('SERVER_TEMPLATES_TTL', '3600'))
SERVER_TEMPLATES_TIMEOUT = float(os.getenv('SERVER_TEMPLATES_TIMEOUT', '15'))

# Steam Workshop metadata. Titles and short descriptions for Workshop item ids,
# fetched from Steam's keyless `GetPublishedFileDetails`. Purely cosmetic plus
# one useful check - whether an id exists at all - so it is safe to turn off on
# a host with no outbound HTTP, and the panel degrades to bare ids.
WORKSHOP_METADATA = os.getenv('WORKSHOP_METADATA', 'true').strip().lower() not in ('0', 'false', 'no', 'off')
WORKSHOP_API_URL = os.getenv(
    'WORKSHOP_API_URL',
    'https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/'
)
# Collections are the keyless way to get a *list* of mods: somebody else's
# curated set, expanded into its items in the order they arranged them.
WORKSHOP_COLLECTION_API_URL = os.getenv(
    'WORKSHOP_COLLECTION_API_URL',
    'https://api.steampowered.com/ISteamRemoteStorage/GetCollectionDetails/v1/'
)
WORKSHOP_API_TIMEOUT = float(os.getenv('WORKSHOP_API_TIMEOUT', '10'))
# Item details change rarely; a day keeps the panel snappy without going stale
# in any way that matters.
WORKSHOP_CACHE_TTL = int(os.getenv('WORKSHOP_CACHE_TTL', '86400'))
# A "no such item" is cached far more briefly: the usual cause is a typo that is
# corrected within the minute.
WORKSHOP_MISS_CACHE_TTL = int(os.getenv('WORKSHOP_MISS_CACHE_TTL', '600'))

# Manager for Game Server Configuration
MANAGE_GAME_SERVERS_CHANNEL = os.getenv('MANAGE_GAME_SERVERS_CHANNEL', 'game_server_managers')

# Manager for Tasks Configuration
MANAGE_TASKS_CHANNEL = os.getenv('MANAGE_TASKS_CHANNEL', 'task_manage')
# Fallback sweep for pending tasks, in case a pub/sub notification is lost.
TASK_SWEEP_INTERVAL = int(os.getenv('TASK_SWEEP_INTERVAL', '60'))
# A task left 'processing' this long is assumed dead (service restart mid-task)
# and is failed so it stops blocking cleanup and reward reconciliation.
TASK_PROCESSING_TIMEOUT = int(os.getenv('TASK_PROCESSING_TIMEOUT', '600'))

# Outbound email. Lives here rather than in the backend for the same reason the
# webhook relay does: the backend has no egress and no DNS, so it cannot reach a
# mail server at all. Blank SMTP_HOST means "no mail server" - the backend then
# logs the message instead, which keeps a developer's signup flow working.
SMTP_HOST = os.getenv('SMTP_HOST', '')
SMTP_PORT = int(os.getenv('SMTP_PORT', '587'))
SMTP_USER = os.getenv('SMTP_USER', '')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD', '')
SMTP_TLS = os.getenv('SMTP_TLS', 'true').strip().lower() not in ('0', 'false', 'no', 'off')
SMTP_FROM = os.getenv('SMTP_FROM', '')
SMTP_TIMEOUT = float(os.getenv('SMTP_TIMEOUT', '15'))

# Webhook alerts. The backend owns the subscriptions and composes the message;
# this container is the only one with egress, so it does the posting - see
# `webhook.py` for why the allowlist there matters. `WEBHOOK_EVENT_QUEUE` is the
# Redis list the manager leaves player/server events on for the backend's
# scheduler to drain; it must match `backend/src/utils/webhooks.py::QUEUE_KEY`.
WEBHOOK_TIMEOUT = float(os.getenv('WEBHOOK_TIMEOUT', '10'))
WEBHOOK_EVENT_QUEUE = os.getenv('WEBHOOK_EVENT_QUEUE', 'webhook:events')
# A cap rather than an unbounded list: if nothing is draining, the useful thing
# to keep is the recent past, not an afternoon of stale joins.
WEBHOOK_EVENT_QUEUE_MAX = int(os.getenv('WEBHOOK_EVENT_QUEUE_MAX', '500'))
WEBHOOK_EVENT_QUEUE_TTL = int(os.getenv('WEBHOOK_EVENT_QUEUE_TTL', '3600'))

# Console command acknowledgement: a server manager reports whether a dispatched
# command actually reached the game server's stdin, under `cmd_ack:<id>`.
COMMAND_ACK_PREFIX = os.getenv('COMMAND_ACK_PREFIX', 'cmd_ack:')
COMMAND_ACK_TIMEOUT = float(os.getenv('COMMAND_ACK_TIMEOUT', '5'))
COMMAND_ACK_TTL = int(os.getenv('COMMAND_ACK_TTL', '60'))
