#!/usr/bin/env python3
"""The in-game item catalog, for picking a reward instead of typing an id.

Why this lives in the manager and not the backend
-------------------------------------------------
The backend sits on the compose `internal` network, which is declared
``internal: true`` - no egress, no DNS to the outside. It cannot reach a wiki,
and giving it egress so that it could would hand outbound network access to the
service that handles authentication and untrusted user input. This container
already needs the internet for SteamCMD, so the one place with egress stays the
one place with egress, and the backend proxies - the same shape as the action
catalog, tasks and mods.

Where the data comes from
-------------------------
`PZwiki:Item_list` on pzwiki.net, fetched as raw wikitext. That page is itself
autogenerated from the game's scripts by `pz-wiki_parser`, so it is a
machine-readable table rather than prose, it carries the game version it was
generated from, and it is one request for the whole catalog (~4,600 items).

What it does **not** cover: mods. The wiki knows base-game items only, so an item
added by a Workshop mod will not appear here and still has to be typed by hand.
The `in_game_id` field stays free text for exactly that reason - this makes the
common case easy without making the uncommon one impossible.

Caching
-------
One Redis key with **no expiry**, refreshed when the stored copy is older than
`ITEM_CATALOG_TTL`. Deliberately not a TTL'd key: an expiry means the first
request after it lapses gets nothing at all if the wiki is unreachable, when a
slightly stale list of item ids would have been perfectly good. A failed refresh
keeps serving what we have and reports why.

Uses `urllib` rather than `requests`, like :mod:`workshop` - this image pins a
deliberately small dependency set and this needs one GET.
"""
import datetime
import json
import re
import time
import urllib.error
import urllib.parse
import urllib.request

import config
import cache


def _log(message):
    ts = datetime.datetime.now().isoformat()
    print(f"[{ts}][Items] {message}")


CACHE_KEY = 'items:catalog'
# Held briefly while one request refreshes, so a cold start with several admins
# does not fetch the same 600KB page several times over.
LOCK_KEY = 'items:catalog:refreshing'
LOCK_SECONDS = 60

# A row is four cells: icon, name, page, item id.
ROW_SEPARATOR = re.compile(r'^\|-\s*$', re.M)
CATEGORY_RE = re.compile(r'<h3[^>]*>(.*?)</h3>', re.S)
FILE_RE = re.compile(r'\[\[File:([^|\]]+)', re.I)
LINK_RE = re.compile(r'\[\[([^|\]]+)(?:\|([^\]]+))?\]\]')
# `Base.Axe`, `Base.Hat_BeretArmy`. The module prefix is always present.
ITEM_ID_RE = re.compile(r'^[A-Za-z0-9_]+\.[A-Za-z0-9_.]+\Z')
VERSION_RE = re.compile(r'\{\{Page version\|([^|}]+)')


def _strip_markup(text):
    """Wiki link markup down to the text a person reads."""
    def replace(match):
        target, label = match.group(1), match.group(2)
        return (label or target).strip()

    cleaned = LINK_RE.sub(replace, text or '')
    cleaned = re.sub(r"'{2,}", '', cleaned)          # bold/italic
    cleaned = re.sub(r'<[^>]+>', '', cleaned)        # stray html
    return ' '.join(cleaned.split())


def parse_item_list(wikitext):
    """Parse the raw wikitext into ``(items, game_version)``.

    Pure, and the only part of this worth testing: everything else is a cache
    around it. Rows that do not end in something shaped like an item id are
    skipped rather than guessed at - the page also contains headers, section
    titles and the occasional note, and inventing an item from one of those
    would put an id into a reward that the game rejects at delivery time.
    """
    items = []
    seen = set()
    category = None

    for block in ROW_SEPARATOR.split(wikitext or ''):
        heading = CATEGORY_RE.search(block)
        if heading:
            category = _strip_markup(heading.group(1)) or None
            continue

        # Cells may be written one per line, which is how this page does it.
        cells = [line[1:].strip() for line in block.splitlines()
                 if line.startswith('|') and not line.startswith('|-')]
        if len(cells) < 4:
            continue

        item_id = _strip_markup(cells[3])
        if not ITEM_ID_RE.match(item_id) or item_id in seen:
            continue
        seen.add(item_id)

        # An item with several colour variants lists several icons; the first is
        # representative and the rest would just make the row noisy.
        icon_match = FILE_RE.search(cells[0])
        icon = icon_match.group(1).strip().replace(' ', '_') if icon_match else None

        name = _strip_markup(cells[1]) or item_id
        page = _strip_markup(cells[2]) or None

        entry = {'id': item_id, 'name': name, 'icon': icon, 'category': category}
        # The page title is usually the display name; only worth sending when it
        # differs, across four thousand rows.
        if page and page != name:
            entry['page'] = page
        items.append(entry)

    version_match = VERSION_RE.search(wikitext or '')
    return items, (version_match.group(1).strip() if version_match else None)


def _fetch():
    """Download and parse the catalog. Returns ``(payload, error)``."""
    request = urllib.request.Request(
        config.ITEM_CATALOG_URL,
        headers={
            # MediaWiki asks clients to identify themselves, and a wiki run by
            # volunteers deserves to know who is asking and where to complain.
            'User-Agent': ('Project-Safezone/1.0 (self-hosted Project Zomboid '
                           'server manager; item catalog; '
                           'https://github.com/gramthanos/Project-Safezone)'),
            'Accept': 'text/plain',
        },
        method='GET',
    )
    try:
        with urllib.request.urlopen(request, timeout=config.ITEM_CATALOG_TIMEOUT) as response:
            text = response.read().decode('utf-8', errors='replace')
    except urllib.error.HTTPError as e:
        return None, f'The wiki returned HTTP {e.code}'
    except urllib.error.URLError as e:
        return None, f'Could not reach the wiki: {e.reason}'
    except (TimeoutError, OSError) as e:
        return None, f'Could not reach the wiki: {e}'

    items, version = parse_item_list(text)
    if not items:
        # A page that fetched fine but parsed to nothing means its layout
        # changed. Saying so is far more useful than an empty picker.
        return None, 'The item list was fetched but nothing could be parsed from it'

    return {
        'items': items,
        'game_version': version,
        'fetched_at': int(time.time()),
        'source': config.ITEM_CATALOG_URL,
        'icon_base': config.ITEM_CATALOG_ICON_BASE,
    }, None


def _read_cache():
    raw = cache.get_value(CACHE_KEY)
    if not raw:
        return None
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return None


def _claim_refresh():
    """True if this request should be the one to go and fetch."""
    r = cache.get_instance()
    if not r:
        return True
    try:
        return bool(r.set(LOCK_KEY, '1', nx=True, ex=LOCK_SECONDS))
    except Exception:
        return True


def get_catalog(force=False):
    """The item catalog. Returns ``(payload, error)``.

    ``payload`` is served from cache whenever there is one, even when a refresh
    failed - a list of item ids from last week is worth far more than an empty
    picker. ``error`` is set when the *refresh* failed, so the panel can say the
    list may be out of date without pretending it has nothing.
    """
    cached = _read_cache()

    fresh_enough = (
        cached
        and not force
        and (time.time() - cached.get('fetched_at', 0)) < config.ITEM_CATALOG_TTL
    )
    if fresh_enough:
        return cached, None

    # Somebody else is already fetching; their result will be along shortly.
    if cached and not force and not _claim_refresh():
        return cached, None

    payload, error = _fetch()
    if error:
        if cached:
            _log(f'Refresh failed, serving the cached copy: {error}')
            return cached, error
        _log(f'Could not build the item catalog: {error}')
        return None, error

    # No expiry on purpose - see the module docstring.
    cache.set_value(CACHE_KEY, json.dumps(payload))
    _log(f"Catalog refreshed: {len(payload['items'])} items, "
         f"game {payload.get('game_version') or 'unknown'}")
    return payload, None
