"""Tests for parsing PZwiki's generated item list.

Only the parse is tested: it is pure, and everything else in `items.py` is a
cache around it. The page is autogenerated, so its shape is stable - but
"stable" is not "guaranteed", which is why a page that fetches fine and parses
to nothing is treated as an error rather than as an empty catalog.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
import items  # noqa: E402


SAMPLE = '''{{Header|PZwiki|Site maintenance}}
{{Page version|42.20.0|2=512551}}
{{Autogenerated|reason=Any changes will be overwritten.}}

{| class="wikitable theme-blue"
|-
! colspan="4"| <h3 style="margin-top:0;">Accessory</h3>
|-
! Icon !! Name !! Page !! Item ID
|-
| [[File:Antler_Headdress.png|32x32px]]
| [[Antler Headdress]]
| [[Antler Headdress]]
| Base.Hat_DeerHeadress
|-
| [[File:Sprayer_Blue.png|32x32px]] [[File:Sprayer_White.png|32x32px]]
| [[Backpack Sprayer]]
| [[Backpack Sprayer]]
| Base.KnapsackSprayer
|-
! colspan="4"| <h3 style="margin-top:0;">Weapon</h3>
|-
! Icon !! Name !! Page !! Item ID
|-
| [[File:Axe.png|32x32px]]
| [[Axe (weapon)|Axe]]
| [[Axe (weapon)]]
| Base.Axe
|-
|
| [[No Icon Item]]
| [[No Icon Item]]
| Base.NoIcon
|-
|}
'''


class TestParseItemList(unittest.TestCase):
    def setUp(self):
        self.items, self.version = items.parse_item_list(SAMPLE)
        self.by_id = {i['id']: i for i in self.items}

    def test_game_version_is_read(self):
        # Worth surfacing: it says which build the ids describe.
        self.assertEqual(self.version, '42.20.0')

    def test_every_row_becomes_an_item(self):
        self.assertEqual([i['id'] for i in self.items],
                         ['Base.Hat_DeerHeadress', 'Base.KnapsackSprayer',
                          'Base.Axe', 'Base.NoIcon'])

    def test_headers_and_section_titles_are_not_items(self):
        self.assertNotIn('Item ID', [i['name'] for i in self.items])

    def test_category_carries_down_the_section(self):
        self.assertEqual(self.by_id['Base.Hat_DeerHeadress']['category'], 'Accessory')
        self.assertEqual(self.by_id['Base.Axe']['category'], 'Weapon')

    def test_first_icon_of_a_variant_row_wins(self):
        self.assertEqual(self.by_id['Base.KnapsackSprayer']['icon'], 'Sprayer_Blue.png')

    def test_piped_link_uses_the_label_not_the_page(self):
        # `[[Axe (weapon)|Axe]]` is displayed as "Axe"; the disambiguated page
        # title is kept separately so it is still linkable.
        self.assertEqual(self.by_id['Base.Axe']['name'], 'Axe')
        self.assertEqual(self.by_id['Base.Axe']['page'], 'Axe (weapon)')

    def test_page_is_omitted_when_it_equals_the_name(self):
        # Four thousand rows; the duplicate is not worth sending.
        self.assertNotIn('page', self.by_id['Base.Hat_DeerHeadress'])

    def test_missing_icon_is_none_rather_than_a_guess(self):
        self.assertIsNone(self.by_id['Base.NoIcon']['icon'])

    def test_rows_without_an_item_id_are_skipped(self):
        text = SAMPLE.replace('| Base.NoIcon', '| not an id at all')
        parsed, _ = items.parse_item_list(text)
        self.assertNotIn('Base.NoIcon', [i['id'] for i in parsed])
        self.assertEqual(len(parsed), 3)

    def test_duplicate_ids_are_collapsed(self):
        parsed, _ = items.parse_item_list(SAMPLE + SAMPLE)
        self.assertEqual(len(parsed), 4)

    def test_empty_and_unrecognised_input(self):
        self.assertEqual(items.parse_item_list(''), ([], None))
        self.assertEqual(items.parse_item_list(None), ([], None))
        self.assertEqual(items.parse_item_list('nothing like a table')[0], [])


if __name__ == '__main__':
    unittest.main()
